### ISSUE TITLE
phar!!

### ISSUE THREAD

**Issue by Infernus102** [ElyWing/ElyWing#2]
### Issue description
Need .phar to start
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* ElyWing-MP: can't use
* PHP: 7.0.3
* Server OS: linux debian 8
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by ankitmaharjan252** [comment]
You can get the latest release from [here](https://github.com/ElyWing/ElyWing/releases/) and download the start.sh from the repo. Rename the phar to ElyWing.phar and start the server!
